-- Enable REPLICA IDENTITY FULL for Realtime tables to ensure complete payloads
ALTER TABLE polls REPLICA IDENTITY FULL;
ALTER TABLE slides REPLICA IDENTITY FULL;
ALTER TABLE options REPLICA IDENTITY FULL;
ALTER TABLE votes REPLICA IDENTITY FULL;
